
-- PIC.CHRISTMAS VIRAL ENGINE SCHEMA
-- Run this in Supabase SQL Editor

-- 1. Users & Auth (Handled by Clerk usually, but we track local profile if needed)
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY, -- Clerk ID
  email TEXT,
  phone TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Referrals System
CREATE TABLE IF NOT EXISTS referrals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  platform TEXT NOT NULL, -- 'whatsapp', 'facebook', etc
  tier TEXT, -- 'tier1', 'tier2', 'tier3'
  status TEXT DEFAULT 'pending', -- 'pending', 'verified'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  expires_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_referrals_user_platform ON referrals(user_id, platform);

-- 3. User Credits (Free Mode & Rewards)
CREATE TABLE IF NOT EXISTS user_credits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  free_photos INTEGER DEFAULT 0,
  paid_photos INTEGER DEFAULT 0,
  total_used INTEGER DEFAULT 0,
  source TEXT, -- 'referral', 'purchase', 'promo'
  expires_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_credits_user ON user_credits(user_id);

-- 4. Share Logs (Analytics)
CREATE TABLE IF NOT EXISTS share_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  platform TEXT,
  referral_link TEXT,
  clicked INTEGER DEFAULT 0,
  converted INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Seed Images (For Viral User Gallery)
CREATE TABLE IF NOT EXISTS seed_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT NOT NULL,
  category TEXT, -- 'christmas', 'santa', 'elf'
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Analytics Events
CREATE TABLE IF NOT EXISTS analytics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL, -- 'view', 'share', 'generate', 'click'
  user_id TEXT,
  metadata JSONB,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Security (RLS)
ALTER TABLE referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_credits ENABLE ROW LEVEL SECURITY;

-- Allow public insert for viral tracking (simplified for launch), enforce logic in backend service role
CREATE POLICY "Enable insert for service role" ON referrals FOR ALL USING (true);
CREATE POLICY "Enable read for users" ON user_credits FOR SELECT USING (auth.uid()::text = user_id);
